Created component product
evgen-kent/AZATI_Workshop pull request #51
Opened 2023-12-19 19:58 UTC by Miracle-229

2023-12-21 10:55 UTC, evgen-kent requested changes
не вижу прилинкованной задачи. изменения в пр не атомарны и не соответсвуют названию ПР. 
Как надо делать читайте в Скайпе написал гайд

2023-12-22 13:23 UTC, Lisovskyiii approved these changes

2023-12-22 13:23 UTC, AlesiaKlemenia approved these changes

2023-12-22 14:32 UTC, evgen-kent approved these changes

2023-12-22 14:45 UTC, merged