connect rating bar to product card
evgen-kent/AZATI_Workshop pull request #65
Opened 2023-12-25 10:06 UTC by Miracle-229

2023-12-25 11:49 UTC, dimskiyy submitted a review, later dismissed

2023-12-26 19:16 UTC, AlesiaKlemenia commented on src/components/ProductCard.tsx
> +				{/* здесь должен быть компонент рейтинга */}
Этот комментарий уже не нужен

2023-12-26 19:20 UTC, AlesiaKlemenia requested changes
В карточках RatingBar должен быть read only.

2023-12-27 14:55 UTC, AlesiaKlemenia approved these changes

2023-12-27 17:36 UTC, dimskiyy submitted a review, later dismissed

2023-12-28 14:25 UTC, puptup requested changes
Думаю, что файлам типа ProductCard.module.scss самое место рядом с файлом, так же предлагаю другую структуру для построения компонентов: 

components/component-name/index.tsx 
рядом с ними будут удобно располагаться файлы со стилями, которые тоже удобно именовать в index.module.scss 

в противном случае, при росте компонентов в будущем будет сплошная путаница и неудобство для чтения кода.

2023-12-31 11:31 UTC, puptup requested changes

2023-12-31 11:31 UTC, puptup commented on src/components/Footer/Footer.tsx
> +import InputBar from '../InputBar/InputBar.tsx'
переименуй файлы по примеру:
InputBar/IntuBar.tsx => input-bar/index.tsx, тогда импорты будут выглядеть так 
import InputBar from '../input-bar'

2023-12-31 11:32 UTC, puptup commented on src/components/Footer/Footer.tsx
> +import InputBar from '../InputBar/InputBar.tsx'
это касается не только этого файла, но и всех остальных

2024-01-02 16:32 UTC, Miracle-229 commented on src/components/Footer/Footer.tsx
> +import InputBar from '../InputBar/InputBar.tsx'
ну на мой взгляд будет путаница , если будет множество файлов index.tsx(особенно если нужно найти нужный во вкладках ) . уж лучше просто переименовать InputBar.tsx => input-bar.tsx

2024-01-02 22:19 UTC, puptup commented on src/components/Footer/Footer.tsx
> +import InputBar from '../InputBar/InputBar.tsx'
> ну на мой взгляд будет путаница , если будет множество файлов index.tsx(особенно если нужно найти нужный во вкладках ) . уж лучше просто переименовать InputBar.tsx => input-bar.tsx

напротив index.tsx всегда есть корневой каталог, где открыт конкретный файл. ну а по поводу навигирования, никогда не обращал внимания на название файла, ибо при грамотной организации компонентов всегда ясно где найти тот или иной файл в дереве каталогов слева в редакторе

тема достаточно холиварная, но я думаю, что стоит это вам на дейлике обсудить

2024-01-03 08:11 UTC, Miracle-229 commented on src/components/Footer/Footer.tsx
> +import InputBar from '../InputBar/InputBar.tsx'
ну обсудить на дейлике это да , а слева в каталоге это сама собой можно найти ) просто удобнее (как по мне) смотреть всё таки сверху во вкладках

2024-01-06 16:29 UTC, Miracle-229 commented on src/components/Footer/Footer.tsx
> +import InputBar from '../InputBar/InputBar.tsx'
мы кстати обговорили тему на созвоне и пришли к тому , что лучше просто оставить файлы , без index.tsx и доп папок

2024-01-10 14:48 UTC, evgen-kent approved these changes

2024-01-10 14:49 UTC, merged