Create action for get/products (for local back)
evgen-kent/AZATI_Workshop pull request #81
Opened 2023-12-31 09:00 UTC by Miracle-229

2023-12-31 11:39 UTC, puptup requested changes

2023-12-31 11:39 UTC, puptup commented on src/store/productSlice.ts
> +export const getProductAction = createAsyncThunk('getProducts', async () => {
мне кажется санкам не самое место в файле со слайсом. думаю, что так как редьюсеров может быть больше одного, их лучше разбить по разным папкам, в которых будут:

nameSlice.ts 
nameSelectors.ts
nameThunk.ts (возможно так же разбив в отдельную папку, если санок будет больше одной)
index.ts (где экспортируются все из файлов/папок)

2023-12-31 11:39 UTC, puptup commented on src/store/productSlice.ts
> +	initialState: {
не вижу тут никакой типизации. откуда мне знать, что помимо статусов idle, loading, succeeded и failed больше ничего нет? 

вынеси инишл стейт наружу слайса, а так же организуй тип, где описан стейт

2023-12-31 11:39 UTC, puptup commented on src/pages/Home/index.tsx
> +			.then(response => {
думаю, что это бэдпрактис. в редаксе есть волшебный хук useSelector. почитай про него и допиши селекторы для данных, которые тебе нужны в этом компоненте

2023-12-31 14:36 UTC, SergeyMurin commented on src/pages/Home/index.tsx
> +			.then(response => {
так же можно написать свой useTypedSelector чтобы все было типизированно, это конечно лишняя писанина. Но в будущем окупится, ты будешь точно знать где что лежит

2023-12-31 15:02 UTC, puptup commented on src/pages/Home/index.tsx
> +			.then(response => {
> так же можно написать свой useTypedSelector чтобы все было типизированно, это конечно лишняя писанина. Но в будущем окупится, ты будешь точно знать где что лежит

не совсем понимаю про что ты, но useSelector типизировать не надо, он возвращает тип на основе пробросанного в него коллбэка селектора. 

я имею ввиду, что в данном кейсе вытягивать данные из диспатча не очень хорошая идея ибо по сути он игнорирует существование стейта и вытягивает данные непосредственно из фетч запроса. по логике, тут useState вообще должен отсутствовать, а на его место придти useSelector.

2024-01-01 15:24 UTC, Miracle-229 commented on src/store/productSlice.ts
> +	initialState: {
спасибо что заметил (а то забыл типизацию привести) ,  а выносить по идее не требуется , можно так оставить 
initialState: {
		data: [] as product[],(где тип продукта )
		status: 'idle',
		error: null as string | null
	},

2024-01-01 15:34 UTC, Miracle-229 commented on src/store/productSlice.ts
> +export const getProductAction = createAsyncThunk('getProducts', async () => {
можно лучше сделать такую структуру уже 
store 
--name
----nameSlice.ts
----nameSelectors.ts
----nameThunk.ts

2024-01-01 15:49 UTC, Miracle-229 commented on src/store/productSlice.ts
> +	initialState: {
или хочешь чтобы было так ? 
type ProductsState = {
  data: product[];
  status: 'idle' | 'loading' | 'succeeded' | 'failed';
  error: string | null;
};

const initialState: ProductsState = {
  data: [],
  status: 'idle',
  error: null,
};

2024-01-01 16:45 UTC, Miracle-229 commented on src/pages/Home/index.tsx
> +			.then(response => {
> думаю, что это бэдпрактис. в редаксе есть волшебный хук useSelector. почитай про него и допиши селекторы для данных, которые тебе нужны в этом компоненте

про useSelector знал ) но думал вот так использовать с простым стейтем

2024-01-01 19:20 UTC, puptup commented on src/store/productSlice.ts
> +	initialState: {
> или хочешь чтобы было так ,всё отдельно 

да, выглядит супер

2024-01-01 19:21 UTC, puptup approved these changes

2024-01-02 08:17 UTC, SergeyMurin approved these changes

2024-01-02 13:40 UTC, merged