component color-picker
evgen-kent/AZATI_Workshop pull request #83
Opened 2024-01-02 14:49 UTC by Lisovskyiii

Features:

Был добавлен компонент выбора цвета. Можно выбирать как один цвет, так и несколько. Кроме этого, добавил функционал скрытия компонента. Был бы рад услышать, что можно поправить.

2024-01-02 22:28 UTC, puptup requested changes

2024-01-02 22:28 UTC, puptup commented on src/components/color-picker/index.tsx
> +const ColorPickerBox = styled(Box)(() => ({
думаю, что нужно определиться, либо использовать на проекте scss, либо styled-components из mui. 

пока что рискну предположить, что можно использовать то и то, но все-таки эти стили лучше вынести в styled.ts

2024-01-02 22:28 UTC, puptup commented on src/components/color-picker/index.tsx
> +const ColorPicker = (): JSX.Element => {
убрать типизацию

2024-01-02 22:28 UTC, puptup commented on src/components/color-picker/index.tsx
> +export default ColorPicker
убери дефолтный импорт

2024-01-02 22:28 UTC, puptup commented on src/components/color-picker/index.tsx
> +				"url(\"data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Cpath" +
обычным svg элементом внутрь реакта это никак не вставить?

2024-01-09 12:38 UTC, AlesiaKlemenia approved these changes

2024-01-10 14:51 UTC, merged