Add mock back
evgen-kent/AZATI_Workshop pull request #98
Opened 2024-01-11 12:22 UTC by Miracle-229

2024-01-11 12:26 UTC, puptup approved these changes

2024-01-11 12:34 UTC, evgen-kent requested changes

2024-01-11 12:34 UTC, evgen-kent commented on src/components/modal-form/modal-form.tsx
> +		// setTimeout(() => window.location.reload(), 1000)
зачем это тут? думаю если это не используется то надо убрать совсем что бы не висело на глазах?

2024-01-11 12:34 UTC, evgen-kent commented on src/api/non-autorization.ts
> +	baseURL: `${process.env.SERVICE_URL}`
```suggestion
	baseURL: `${process.env.SERVICE_URL  || 'https://azati-workshop-be.fly.dev/'}`
```

2024-01-11 12:34 UTC, evgen-kent commented on src/api/non-autorization.ts
> +	baseURL: `${process.env.SERVICE_URL}`
что бы по умолчанию локально на localhost запрос шел
и чуть что можно было в env файле регулировать

2024-01-11 16:11 UTC, puptup submitted a review, later dismissed

2024-01-12 09:57 UTC, Miracle-229 commented on src/components/modal-form/modal-form.tsx
> +		// setTimeout(() => window.location.reload(), 1000)
убрано

2024-01-12 10:14 UTC, evgen-kent requested changes

2024-01-12 10:14 UTC, evgen-kent commented on vite.config.ts
> +	process.env = { ...process.env, ...loadEnv(mode, process.cwd()) }
пинг

2024-01-12 10:16 UTC, Miracle-229 commented on src/api/non-autorization.ts
это если придётся поменять api для не авторизованный пользователей . но пока у нас такого функционала нет , так что убрано

2024-01-12 10:16 UTC, Miracle-229 commented on src/api/autorization.ts
> +		import.meta.env.VITE_SERVICE_URL || 'https://azati-workshop-be.fly.dev/'
убрано

2024-01-12 10:17 UTC, Miracle-229 commented on vite.config.ts
> +	process.env = { ...process.env, ...loadEnv(mode, process.cwd()) }
это для vite решение увидел здесь - https://stackoverflow.com/questions/66389043/how-can-i-use-vite-env-variables-in-vite-config-js и оно заработало

2024-01-12 10:18 UTC, Miracle-229 commented on vite.config.ts
> +	process.env = { ...process.env, ...loadEnv(mode, process.cwd()) }
без этого не работала чего-то подгрузка env на проде

2024-01-12 11:06 UTC, merged

2024-01-12 11:19 UTC, evgen-kent commented on src/store/registration/registrationSlice.ts
>  const initialState: registrationState = {
все сущности тайп скрипта принято всегда с большой буквы писать `const initialState:    RegistrationState`